# Dart kod analizatori uchun sozlamalar.
# Bu yerda loyihada amal qilinishi kerak bo'lgan qoidalar belgilanadi.
include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - prefer_final_fields
    - prefer_const_constructors
    - curly_braces_in_flow_control_structures
    - empty_catches
    # Qo'shimcha qattiqqo'l qoidalar
    - prefer_final_locals
    - unnecessary_this
    - unawaited_futures