# pubspec.yaml

name: chat_backend
description: A robust and scalable backend for a real-time chat application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0' # Eng so'nggi Dart versiyasidan foydalanish

dependencies:
  # Web server uchun asos
  shelf: ^1.4.1
  shelf_router: ^1.1.4

  # Ma'lumotlar bazasi (PostgreSQL uchun eng yaxshi variantlardan)
  postgres: ^3.0.0 # Agar boshqa DB ishlatsangiz, shunga mos paketni tanlang

  # Parol xavfsizligi uchun (eng zamonaviy standart)
  crypt: ^4.3.1

  # JWT (JSON Web Tokens) bilan ishlash uchun
  dart_jsonwebtoken: ^3.2.0

  # .env faylidan xavfsiz konfiguratsiya o'qish uchun
  envied: ^1.1.1

  # Unikal IDlar generatsiyasi uchun
  uuid: ^4.4.0
  
  # Xatolik yoki Muvaffaqiyatni chiroyli boshqarish uchun
  fpdart: ^1.1.0


dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.4.10
  envied_generator: ^1.1.1