# pubspec.yaml

name: chat_app_backend
description: A scalable and production-ready Dart backend for a chat application.
version: 1.0.0
# Bu loyiha pub.dev ga joylanmasligini bildiradi
publish_to: 'none'

environment:
  # Eng so'nggi Dart SDK'sini talab qiladi
  sdk: '>=3.0.0 <4.0.0'

# Asosiy bog'liqliklar
dependencies:
  # --- SERVER ---
  shelf: ^1.4.1
  shelf_router: ^1.1.4

  # --- DATABASE ---
  # PostgreSQL bilan ishlash uchun rasmiy paket
  postgres: ^3.0.0

  # --- UTILS & HELPERS ---
  # Dependency Injection uchun
  get_it: ^8.0.3
  # .env fayllaridan o'qish uchun
  dotenv: ^4.2.0
  # Funktsional dasturlash uchun (Either, Option)
  dartz: ^0.10.1
  # Xavfsiz parol heshlash (bcript)
  bcrypt: ^1.1.3
  # JWT tokenlarni yaratish va tekshirish uchun
  dart_jsonwebtoken: ^3.2.0
  # Noyob ID (UUID) generatsiyasi uchun
  uuid: ^4.5.1
  # SMTP orqali email yuborish uchun
  mailer: ^6.1.0
  # Qiymatga asoslangan tenglik va hashCode'ni osonlashtirish uchun
  equatable: ^2.0.5
  # Modellar uchun JSON serializatsiya/deserializatsiya annotatsiyalari
  json_annotation: ^4.9.0
  # Loglarni yozib borish uchun
  logging: ^1.2.0
  args: ^2.7.0

# Faqat ishlab chiqish jarayonida kerak bo'ladigan bog'liqliklar
dev_dependencies:
  # Tavsiya etilgan linter qoidalari to'plami
  lints: ^6.0.0
  # Test yozish uchun
  test: ^1.24.0
  # Kod generatsiyasi uchun
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
flutter:
  assets:
   - .env